// <auto-generated />
namespace MyCompany.MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_DictionaryType_DictionaryItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_DictionaryType_DictionaryItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050319207_add_DictionaryType_DictionaryItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
